# Generated by Django 5.0 on 2024-08-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profile_img/'),
        ),
    ]
